AwsRegion: "ca-central-1"
CoDomain: "www.shorthillstreeservice.com"
CoEmail: "info@shorthillstreeservice.com"
CoPhone: "(905) 892-0261"
DbCluster: "cluster0.q0zlz.mongodb.net"
DbName: ""
DbPassword: ""
DbUser: "main"
HST: "83590 3097 RT0001"
LogoURI: "https://shts-pdf.s3.ca-central-1.amazonaws.com/public/logo2.png"
SsmPath: "shts-pdf-gen"
Stage: "prod"