AwsRegion: "ca-central-1"
CoAddress1: "421 Poth St."
CoAddress2: "Welland, Ontario, Canada L3B 5NB"
CoName: "Shorthills Tree Service"
CoDomain: "www.shorthillstreeservice.com"
CoEmail: "info@shorthillstreeservice.com"
CoPhone: "(905) 892-0261"
DbCluster: "peer0.mvx5f.mongodb.net"
DbLocalHost: 192.168.86.137
DbName: "shorthills"
HST: "83590 3097 RT0001"
LogoURI: "https://shts-pdf.s3.ca-central-1.amazonaws.com/public/logo2.png"
S3Bucket: "shts-pdf"
Stage: "prod"